### ISSUE TITLE
Allow setting Sakura specific CSS styles

### ISSUE THREAD

**Issue by sanel** [dabisu/sakura#61]
From what I could see in the code, Sakura does not have ability to set custom css styles, specific only to Sakura window. For example, this can be useful for setting custom tab size or colors that will not affect other gtk apps.

Here is a small patch that will introduce `sakura` css id, which can be further referenced in `gtk.css` file.

```patch
diff --git a/src/sakura.c b/src/sakura.c
index f137879..16b77da 100644
--- a/src/sakura.c
+++ b/src/sakura.c
@@ -2307,6 +2307,7 @@ sakura_init()
 	/* Create our windows */
 	sakura.main_window = gtk_window_new(GTK_WINDOW_TOPLEVEL);
 	gtk_window_set_title(GTK_WINDOW(sakura.main_window), "sakura");
+	gtk_widget_set_name(sakura.main_window, "sakura");
 
 	sakura.fade_window = gtk_window_new(GTK_WINDOW_POPUP);
 	gtk_widget_set_name(sakura.fade_window, "fade_window");
```

After this, setting Sakura specific (black) tabs will work with eg. (put it in `~/.config/gtk-3.0/gtk.css`):
```css
@define-color black #000000;

#sakura notebook tab {
    background-color: @black;
    min-height: 10px;
    padding: 0;
    margin: 0;
}

#sakura notebook tab:active {
    background-color: @black;
}

#sakura notebook tab label {
    color: white; /* optional: to make the label visible on black */
    padding: 0;
    margin: 0;
}
```

If you are interested I can create PR for this, but the change is so small so I put diff directly in this ticket. I'm not sure if this covers all the edge cases, but works from my initial testing.
